<?php

echo '
{
  "menu":{
    "child1":{
      "type":"CircleAvatar",
      "Name":"username",
      "content":"dosent matter",
      "fontSize":19,
      "color":[
        0,
        0,
        0
      ],
      "backgroundColor":[
        68,
        138,
        255
      ]
    },
    "child4":{
      "type":"ListTile",
      "content":"log in",
      "onPress":"pushAndReplacement(screen3);"
    },
    "child3":{
      "type":"FlatButton",
      "content":"log in",
      "onPress":"pushAndReplacement(screen3);"
    },
    "child2":{
      "type":"Image",
      "height":0.30,
      "content":"https://less-code.000webhostapp.com/appImagesFile/app_id_qwer/tstimage.jpg"
    }
  },
  "screen0":{
    "menu":"off",
    "appBar":"home",
    "appBarColor":[
      68,
      138,
      255
    ],
    "screenColor":[
      250,
      250,
      250
    ],
    "body":{
      "child2":{
        "type":"FlatButton",
        "onPress":"push(screen1);",
        "content":"sign up",
        "position":[
          0.0,
          -0.25
        ],
        "height":0.07,
        "width":0.50,
        "backgroundColor":[
          68,
          138,
          255
        ],
        "fontSize":18,
        "color":[
          255,
          255,
          255
        ]
      },
      "child1":{
        "type":"FlatButton",
        "onPress":"push(screen3);",
        "content":"log in",
        "position":[
          0.0,
          0.0
        ],
        "height":0.07,
        "width":0.50,
        "backgroundColor":[
          68,
          138,
          255
        ],
        "fontSize":18,
        "color":[
          255,
          255,
          255
        ]
      },
      "child3":{
        "type":"List",
        "position":[
          0.0,
          0.99
        ],
        "height":0.30,
        "width":0.80,
        "backgroundColor":[
          68,
          138,
          255
        ],
        "child1":{
          "type":"ListTile",
          "content":"ListTile1",
          "onPress":"push(screen1);",
          "subContent":"this is subContent"
        },
        "child2":{
          "type":"ListTile",
          "content":"ListTile2",
          "onPress":"push(screen1));",
          "color":[
            255,
            0,
            0
          ],
          "backgroundColor":[
            0,
            255,
            0
          ]
        },
        "child3":{
          "type":"ListTile",
          "content":"ListTile3",
          "onPress":"push(screen1));"
        },
        "child4":{
          "type":"ListTile",
          "content":"ListTile4",
          "onPress":"push(screen1);"
        },
        "child5":{
          "type":"ListTile",
          "content":"ListTile5",
          "onPress":"push(screen1);"
        },
        "child6":{
          "type":"ListTile",
          "content":"ListTile6",
          "onPress":"push(screen1);"
        },
        "child7":{
          "type":"ListTile",
          "content":"ListTile7",
          "onPress":"push(screen1);"
        },
        "child8":{
          "type":"ListTile",
          "content":"ListTile8",
          "onPress":"push(screen3);"
        },
        "child9":{
          "type":"ListTile",
          "content":"ListTile9",
          "onPress":"push(screen3);"
        },
        "child10":{
          "type":"ListTile",
          "content":"ListTile10",
          "onPress":"push(screen3);"
        },
        "child11":{
          "type":"ListTile",
          "content":"ListTile11",
          "onPress":"push(screen3);"
        },
        "child12":{
          "type":"ListTile",
          "content":"ListTile12",
          "onPress":"push(screen3);"
        },
        "child13":{
          "type":"FlatButton",
          "onPress":"push(screen1);",
          "content":"sign up",
          "position":[
            "dosent matter if its in the list"
          ],
          "height":0.07,
          "backgroundColor":[
            68,
            138,
            255
          ],
          "fontSize":18,
          "color":[
            255,
            255,
            255
          ]
        }
      },
      "child4":{
        "type":"ListTile",
        "content":"example for listTile",
        "subContent":"ListTile12",
        "onPress":"push(screen3);",
        "position":[
          0.0,
          -0.80
        ],
        "backgroundColor":[
          68,
          138,
          255
        ],
        "height":0.07,
        "width":1.0
      }
    }
  },
  "screen1":{
    "menu":"off",
    "appBar":"sign up",
    "appBarColor":[
      68,
      138,
      255
    ],
    "screenColor":[
      255,
      255,
      255
    ],
    "body":{
      "child2":{
        "type":"FlatButton",
        "onPress":"insertion();push(screen2);",
        "content":"تسجيل ",
        "position":[
          0.0,
          -0.25
        ],
        "height":0.07,
        "width":0.50,
        "backgroundColor":[
          68,
          138,
          255
        ],
        "fontSize":18,
        "color":[
          255,
          255,
          255
        ]
      },
      "child1":{
        "type":"Input",
        "Name":"username",
        "content":"enter your Name",
        "position":[
          0.0,
          0.30
        ],
        "width":0.70
      }
    }
  },
  "screen2":{
    "menu":"on",
    "appBar":"welcome",
    "appBarColor":[
      68,
      138,
      255
    ],
    "screenColor":[
      255,
      255,
      255
    ],
    "body":{
      "child1":{
        "type":"CircleAvatar",
        "Name":"username",
        "content":"dosent matter",
        "position":[
          0.0,
          0.25
        ],
        "height":0.30,
        "width":0.50,
        "fontSize":24,
        "color":[
          0,
          0,
          0
        ],
        "backgroundColor":[
          68,
          138,
          255
        ]
      }
    }
  },
  "screen3":{
    "menu":"on",
    "appBar":"Login",
    "appBarColor":[
      68,
      138,
      255
    ],
    "screenColor":[
      150,
      150,
      150
    ],
    "body":{
      "child2":{
        "type":"FlatButton",
        "onPress":"validation();push(screen2);",
        "content":"تسجيل الخول ",
        "position":[
          0.0,
          -0.25
        ],
        "height":0.07,
        "width":0.50,
        "backgroundColor":[
          68,
          138,
          255
        ],
        "fontSize":18,
        "color":[
          255,
          255,
          255
        ]
      },
      "child1":{
        "type":"Input",
        "Name":"username",
        "content":"enter your Name",
        "position":[
          0.0,
          0.30
        ],
        "width":0.70
      }
    }
  }
}
';

?>